version: '3'
services:
  k6:
    image: grafana/k6
    command: run
    volumes:
      - ./scenarios:/scenarios
      - ./output:/output
    environment:
      HOST: "http://host.docker.internal:8080"
